### ISSUE TITLE
Make wrapper regeneration deterministic

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-workflows-kt#208]
See #206 - wrappers check failed because in the meantime, some action unrelated to this PR got a new input.

As the number of supported actions grows, such unrelated failures will be more and more frequent. They happen because each time, the newest commit of a given action version is taken.

Possible remedy: have a lock file, similarly to NPM or Yarn. The file would contain mapping from action name and major version to commit hash. This way wrapper regeneration becomes deterministic with respect to the inputs and all its other parameters. There should be also a mechanism to update these commit hashes, ran on demand and checked by a job. This way we preserve checking if the wrappers cover all existing inputs, and prevent failing workflow runs on the main branch.

**Comment by jmfayard** [comment]
I think this is a bad developer experience not mostly for the maintainers but for the newcomers.
It's hard to discover a new project, become familiar with the codebase, the conventions and everything. 
Still you do your best and after all this effort... you get a feedback by email from GitHub Action that you broke something.
You are a bit disappointed, you try to understand the cryptic error message.
It doesn't look related to what you did, you are confused.

There must be some way to improve that eperience

**Comment by krzema12** [comment]
@jmfayard yeah, I realize all of this, it's just my conscious tradeoff to focus on more important stuff. Would you like to contribute by fixing the issue you mentioned?

**Comment by krzema12** [comment]
WIP: https://github.com/krzema12/github-workflows-kt/tree/get-commit-for-branch
