### ISSUE TITLE
[Bug] check_yaml_consistency broken after rename

### ISSUE THREAD

**Issue by jmfayard** [krzema12/github-workflows-kt#491]
# Action

Help with the renaming of the project 

See https://github.com/krzema12/github-workflows-kt/pull/490

# Expected

The workflows should still run

# Actual

check_yaml_consistency is broken for now

https://github.com/krzema12/github-workflows-kt/actions/runs/3243958793/jobs/5319436742#logs

```diff
Run git diff --exit-code '.github/workflows/build.yaml'
 # This file was generated using Kotlin DSL (.github/workflows/build.main.kts).
 # If you want to modify the workflow, please change the Kotlin file and regenerate this YAML file.
-# Generated with https://github.com/krzema12/github-workflows-kt
+# Generated with https://github.com/krzema12/github-actions-kotlin-dsl
```

# Workaround, if exists

I don't know.

# Library version

`@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:0.28.0")`

**Comment by krzema12** [comment]
Weird, I cannot reproduce it. Let me close for now.
