### ISSUE TITLE
[Action wrapper(s) request] madhead/intellij-http-client-action

### ISSUE THREAD

**Issue by madhead** [krzema12/github-workflows-kt#593]
### Are you sure the action(s) you want aren't already supported?

No, it's not supported

### What action(s) do you need?

- [madhead/intellij-http-client-action](https://github.com/marketplace/actions/intellij-http-client-action) @ GitHub Marketplace
- [madhead/intellij-http-client-action](https://github.com/madhead/intellij-http-client-action) @ GitHub

**Comment by krzema12** [comment]
@madhead it looks like the `v0` major version tag disappeared from the action's repo, it was present when we merged your PR: https://github.com/krzema12/github-workflows-kt/pull/594/files and it's necessary for the action wrapper to be exist, according to the docs: https://krzema12.github.io/github-workflows-kt/user-guide/using-actions/#requirements-for-adding-a-new-action. Please restore the tag and let me know in this issue.
