### ISSUE TITLE
Not succeeding in excuting "check_yaml_consistency"

### ISSUE THREAD

**Issue by S-H-Y-A** [krzema12/github-workflows-kt#598]
# Action

_Describe what you are trying to do._

I would like to excute refreshVersions and create a kts.
https://gist.github.com/S-H-Y-A/64e92ebb62799934277ac0a99c473e80

# Expected

RefreshVersion will be excuted.

# Actual

Throwed error before excute _Refresh-Versions_ job:
`/home/runner/work/_temp/8d8792f9-3d76-4160-904d-057ca2980cea.sh: line 1: .github/workflows/refreshVerions.main.kts: Permission denied`
![image](https://user-images.githubusercontent.com/74596628/210169321-0cad9cbc-1ae6-4d73-9bbe-5f6d31c4aea7.png)

But I think I cannot permit to access these file on GitHub Actions with github-workflows-kt. How to solve it?

# Library version

v0.33.0

**Comment by krzema12** [comment]
Hi @S-H-Y-A! Please make the script executable, e. g. on Linux:

```
chmod +x filename
```

**Comment by S-H-Y-A** [comment]
Actually, I I tried it. Then, I got another error:
```
Run git diff --exit-code '.github/workflows/refreshVersions.yaml'
diff --git a/.github/workflows/refreshVersions.yaml b/.github/workflows/refreshVersions.yaml
old mode 100755
new mode 100644
Error: Process completed with exit code 1.
```

**Comment by krzema12** [comment]
Hmm, something's off here. We've never had these issues. Could you point me to a reproducer?

**Comment by S-H-Y-A** [comment]
https://github.com/S-H-Y-A/GitHubWorkFlowKtTestSample 
This Repository is a sample.

**Comment by S-H-Y-A** [comment]
And this is an example:
https://github.com/S-H-Y-A/GitHubWorkFlowKtTestSample/actions/runs/3823685642

**Comment by krzema12** [comment]
@S-H-Y-A can you just modify the chmod of the YAML file, like the diff suggests? Alternatively, remove the YAML and regenerate it.

**Comment by S-H-Y-A** [comment]
```
diff --git a/.github/workflows/refreshVersions.yaml b/.github/workflows/refreshVersions.yaml 
old mode 100**755** 
> > new mode 100**644**
```

This means that the file which is uploaded on GitHub by me is 755 mode and that the other file which is regenerated by GitHub Actions is 644 mode.

If I uploades the 644 mode fIle,
GitHub would throw error: `Permission denied` because a 644 mode file couldn't be removed.

**Comment by krzema12** [comment]
I [forked](https://github.com/krzema12/GitHubWorkFlowKtTestSample) your reproducer repo and added [a commit](https://github.com/krzema12/GitHubWorkFlowKtTestSample/commit/d160032689422b060bf2ef882702d006c96c6d74) that removes execution permission for the YAML:

![image](https://user-images.githubusercontent.com/3110813/210317359-fd9da275-ea42-4dc7-a630-1d98f5cbf030.png)

The consistency check succeeded: https://github.com/krzema12/GitHubWorkFlowKtTestSample/actions/runs/3827731785/jobs/6512569175 and refreshVersions created this PR: https://github.com/krzema12/GitHubWorkFlowKtTestSample/pull/1

You wrote:

> If I upload the 644 mode fIle, GitHub will throw error: `Permission denied` because a 644 mode file cann't be removed when GitHubActions execute `Executes Script, check_yaml_consistency.`

I don't see an workflow run in your repo that shows this. Could you provide a reproduction for it? My above change shows that 644 works fine.

**Comment by S-H-Y-A** [comment]
![755466](https://user-images.githubusercontent.com/74596628/210336514-ede3dac6-ae33-428c-95b1-a717c9d384eb.png)
I made both 644 and 755 workflows, and both throw error which is different from each other.
[Commit](https://github.com/S-H-Y-A/GitHubWorkFlowKtTestSample/commit/77c17806c2a2b46fcd3a519540434082dae3d58b)
[Actions: RefreshVersions-644 #1](https://github.com/S-H-Y-A/GitHubWorkFlowKtTestSample/actions/runs/3828548767)
[Actions: RefreshVersions-755 #1](https://github.com/S-H-Y-A/GitHubWorkFlowKtTestSample/actions/runs/3828549356)

**Comment by krzema12** [comment]
The Kotlin script always has to be executable.

**Comment by S-H-Y-A** [comment]
Thank you.
I solve this probrem with it.
 I'm sorry for the trouble.
