### ISSUE TITLE
[Action wrapper(s) request] burrunan/gradle-cache-action

### ISSUE THREAD

**Issue by Vampire** [krzema12/github-workflows-kt#641]
In case you wonder about the difference to `gradle/gradle-build-action`, it is was there before the "official" action and it has better features in regards to caching. See https://linen.dev/s/gradle-community/t/8479731/how-do-you-enable-the-cache-on-github-actions-i-thought-usin for some facts about the differences.

### Are you sure the action(s) you want aren't already supported?

Yes

### What action(s) do you need?
_URL to GitHub, e.g.: https://github.com/burrunan/gradle-cache-action_

### Do the actions fulfill all [the requirements](https://krzema12.github.io/github-workflows-kt/user-guide/using-actions/#requirements-for-adding-a-new-action)?

Yes

**Comment by Vampire** [comment]
Request to add action typings: https://github.com/burrunan/gradle-cache-action/issues/58

**Comment by krzema12** [comment]
@Vampire I see the typings are already merged in the action, cool! If you convince the maintainer to release a new version within several days, we can make use of them in the next release of the lib :)

**Comment by Vampire** [comment]
No convincing needed. :-D
I said he is quite active, when you wrote that comment it was already released 1.5 hours.. :-)
(Besides of the tag-problem)

**Comment by Vampire** [comment]
No convincing needed. :-D
I said he is quite active, when you wrote that comment it was already released 1.5 hours.. :-)
(Besides of the tag-problem)
